version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    expose:
      - 8000
    build:
      context: ./services/api
      dockerfile: ../../docker/api.Dockerfile
    depends_on:
      db:
        condition: service_started
      rabbit:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./services/api:/api
      - ./lib/shared:/api/shared
      - ./assets:/assets

  consumer:
    expose:
      - 8000
    build:
      context: ./services/api
      dockerfile: ../../docker/api.Dockerfile
    depends_on:
      rabbit:
        condition: service_healthy
      db:
        condition: service_started
    env_file:
      - .env
    volumes:
      - ./services/consumer:/consumer
      - ./lib/shared:/consumer/shared
      - ./assets:/assets

  instagram:
    expose:
      - 8000
    build:
      context: ./services/inst
      dockerfile: ../../docker/inst.Dockerfile
    env_file:
      - .env
    volumes:
      - ./services/inst:/inst
      - ./assets:/assets

  payment:
    expose:
      - 8000
    build:
      context: ./services/payment
      dockerfile: ../../docker/payment.Dockerfile
    env_file:
      - .env
    volumes:
      - ./services/payment:/payment
      - ./assets:/assets

  rabbit:
    image: rabbitmq:3.11.16-management-alpine
    env_file:
      - .env
    volumes:
      - ./rabbitmq/delayed_message_exchange.ez:/opt/rabbitmq/plugins/delayed_message.ez
      - ./rabbitmq/enabled:/etc/rabbitmq/enabled_plugins
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data: